
namespace CommunicationLibrary
{
    public enum ControllerMessage
    {
        NONE = 0,
        CONTROLLER_CONNECT_USB = 1,
        CONTROLLER_CONNECT_BT = 2,
        CONTROLLER_CONNECT = 3,
        CONTROLLER_DISCONNECT_USB = 4,
        CONTROLLER_DISCONNECT_BT = 5,
        CONTROLLER_DISCONNECT = 6,
        CONTROLLER_BATTERY_CHANGE = 7,
        CONTROLLER_TOUCHPAD_CHANGE = 8,
        CONTROLLERS_EXCLUSIVE_MODE = 9,        
        CONTROLLER_LED_COLOR = 11,
        CONTROLLER_LED_FLASH = 12,
        CONTROLLER_LED_BATTERY = 13,
        CONTROLLER_LED_DISCHARGE = 14,
        CONTROLLER_TOUCH_VALUE = 15,
        CONTROLLER_TOUCH_TAP = 16,
        CONTROLLER_TOUCH_SCROLL = 17,
        CONTROLLER_TOUCH_STARTUP = 18,
        CONTROLLER_TOUCH_JITTER = 19,
        CONTROLLER_TOUCH_RIGHT = 20,
        CONTROLLER_RUMBLE_BOOST = 21,
        CONTROLLER_RUMBLE_HEAVY = 22,
        CONTROLLER_RUMBLE_LIGHT = 23,
        CONTROLLER_RUMBLE_SWAP = 24,
        CONTROLLER_TUNING_LEFT = 25,
        CONTROLLER_TUNING_RIGHT = 26,
        CONTROLLER_TUNING_IDLE = 27,
        CONTROLLER_TUNING_REALTIME = 28,
        CONTROLLER_TUNING_FLUSH = 29,
        CONTROLLER_TUNING_GYRO = 30
    }
}
