
namespace CommunicationLibrary
{
    public enum ControllerMessage
    {
        NONE = 0,
        CONTROLLER_CONNECT_USB = 1,
        CONTROLLER_CONNECT_BT = 2,
        CONTROLLER_CONNECT = 3,
        CONTROLLER_DISCONNECT_USB = 4,
        CONTROLLER_DISCONNECT_BT = 5,
        CONTROLLER_DISCONNECT = 6,
        CONTROLLER_BATTERY_CHANGE = 7,
        CONTROLLER_TOUCHPAD_CHANGE = 8,
        CONTROLLERS_EXCLUSIVE_ENABLED = 9,
        CONTROLLERS_EXCLUSIVE_DISABLED = 10
    }
}
